name: Android Build

on:
  push:
    branches: [ master, master-alpha ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: cd calibration-app; ./gradlew assembleRelease -PkeystorePassword=${{secrets.KEYSTORE_PASSWORD}} -PkeyAliasPassword=${{secrets.KEY_ALIAS_PASSWORD}}
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        appName: ${{secrets.APPCENTER_ORGANIZATION}}/${{secrets.APPCENTER_APP}}
        token: ${{secrets.APPCENTER_API_TOKEN}}
        group: Internal
        file: calibration-app/app/build/outputs/apk/release/app-release.apk
